server:
  api:
    basePath: /api/v1
    docs: api-docs
    host: localhost
    port: 3000
    whitelist: ['http://localhost:3000', 'http://localhost:4200']
  auth:
    accessToken: 'SecretAccessToken'
    testToken: 'SecretTestToken'
    jwtSecret: 'SecretJwtToken'
    jwtExpiresIn: '7d'
  db:
    authSource: admin
    database: salespal
    host: localhost
    logging: false
    name: default
    password: root
    port: 27017
    username: admin
  socket:
    host: localhost
    path: /api-socket
    port: 3000
